---
title: "Daily Research Blog 2025"
author: Paityn Richardson
subtitle: Data Science Curriculum 
---

## Date: May 19

1. Read through the beginning half of PAYS curriculum and took notes in a google doc. 
2.  Finish reading through the rest and take notes on the structure of problems. 
3. I'm still a little confused about the physical logistics of computers in the classroom. It looks like the students mostly work in groups already, so maybe shared devices with a server connection would work, so every student doesn't need to download on their own device?

## Date: May 20th

1. Continued Reading through Pays curriculum. Created an infographic for teaching the difference between Quantitative and Categorical variables. Re-wrote a few problems what used excel in r. 
2. Find more problems that cant be shifted from excel to r usage. 
3. How is material typically taught during the program. Is it similar to a college lecture with slideshow presentation? I wanted to start thinking about teaching materials for information but i realized i not sure how material is usually taught.

## Date: May 21st 

1. Re wrote section 5.2 in Latex and a Quarto document. Marked down and started writing example questions that involved excel usage. 
2. Discuss whether I should try to continue in Latex or if it would be beneficial to switch to quarto. 
3. Same as question 2 but I'm not sure how easy it is to view images in Latex, which makes it difficult to explain certain topics. Its much clearer in a quarto doc, but have to deal with problems of combining work with current curriculum. 

## Date: May 23rd
1. Gave presentation during pizza and progress. Added more to section 5.2 about tidyverse function and their use. Figured out Latex highlighting syntax. 
2. I will start going through the other examples of excel use in the curriculum and rewrite them in r following the structure i have been using to write 5.2, 
3. I'm not sure if i like how the highlighting looks when rendered in the pdf. I'm nervous that it looks to dissimilar to r and it will be hard for students to follow. I also don't love how the future lines are sill very visible so it doesn't really help to promote the step by step process we were trying to achieve.

## Date: May 27th
1. Updated some styling choices in 5.2 re write. Took out latex code and just opted for displaying individual steps through lines of r code. Found 2 example problems in the Pays curriculum. Modeling Growth and Decay and Planetary Orbits. Re wrote both problems in r with solutions in all in a pdf. 
2. Start re write for the Simple Pendulum Problem in pays curriculum which includes work in excel. Also I am going to have someone proof read my writing for grammar and spelling errors and make sure it is digestible for someone with minimal R background. 
3. Is there an easier way to display an exponential model in r, because right now i am just fitting the curve by linearizing the model first. Also the displaying of the equation is a little difficult in R, but i figure that is also work that will be done on paper and its just helpful to have the solutions all in one place. Also am still a little bit confused (or maybe i forgot) what your goal or vision was for the different documents to come out of this project. Is there a separate one with just solutions or should solutions and questions all be together. And is there a separate doc with interactive prompts for each question, if so that will be next thing on my to-do list for 5.2. 

## Date: May 28th 
1. I added a section to 5.2 about linear vs. non linear models. Since a lot of the in class activities involve examining either linear or non linear models, i thought it would be important to give the basic instructions here. I want to ask about labeling sections because it could be good to refer back to this specific sections when reading the in class activities. Created pdf for the simple pendulum problem with solutions and instructions. I also started reading some of the material in the data 4 all repo and found a good presentation about asking good questions. I think this could be a good topic for just starting out with data science materials. 
2. Going to start forming the interactive versions of each of the in class activities. This will be a qmd file with minimal instructions that students can open up and type directly into. I also need to upload all the example data sets i have created somewhere so that students can access them and don't have to type data into excel.
3. I want to add a section about asking good questions or how to formulate questions about data. I'm not sure if this would be better as something similar to 5.2 where its instructions based. Or have a string of homework problems that outline different data sets and just have students come up with questions and discuss with TA's and peers. I also think that most of the examples i am re writing come from the in-class activities section of the curriculum so i was wondering if it would it be worth it to just re write that whole section in r. That way there can just be a separate pdf with in class activities. 

## Date: May 29th
1. Wrote the R integrated version for the radioactive decay in class activity. Then i read and took notes on the data4all lessons to figure out how to formulate questions and lesson plans better. Finally i created an interactive qmd file with some sample homework questions. I broke the questions up into different categories that outline the basic skills expected to be gained from the curriculum. 
2. I plan start compiling some of the documents I have into one file. Also, now that i have some experience writing interactive forms of questions, I am going to start updating some of the in class activities so there are versions of the files with less writing/explanation and instead just the questions and answers. 
3. I What will the next steps be in th project? From my perspective, i want to be able to connect all the information needed to complete the in class activities to some sort of interactive homework assignment or lesson. I also think it would be beneficial to have some kinds of visual aids or lesson materials to help foster learning, but i don't know how cohesive that would be with the structure of the program. maybe the next step is just to condense materials and organize them neatly in github, but also there was maybe ideas of an interactive course site? I would be interested in that. 

## Date: May 30th 
1. I separated each of the In-Class activities into three different files: activity_intructions, activity_interactive, and activity_solutions. I also create a qmd file for each activity called ICA.activityname.qmd. This file has a short description of the activity and explains how to use the document or where(hypothetically) to find the version you need. I also created separate folders for each of these activities in my work. 
2. Number 2 nd 3 kind of go hand in hand today but i need to meet with you to fix some stuff/ discuss where to put datasets to avoid having 2 copies of each one is the repo, because one needs to be in the folder with the activity so it can be read in, but I originally had them all in a folder called datasets, which would have been helpful for organizational purposes. 
3. I am a little stuck with rendering right now because, for some reason eval: false condition is not working when i am trying to render. I thought maybe it was because my qmd's didnt have yaml headers but i looked into it and coulnt find anywhere that said that. I also tried adding a header and it did not help. It might be something with the include sytax that i need to update but for now its difficult because lal of my interactive documents hve a lot of un-renderable code... Im sure its probably a simple fix which is why i just focused on writing up all the documents first.  
 

## Date: June 2nd 
1. Finished the integrated documents for all of the in class activities. This included rendering each one to both pdf and html forms. I added an activity for Hooke's Law and Area of stars, which i previously did not have before. I also created a separate sections for homework problems/assignments in my work. I noticed that a lot of the in class problems, like the in class activities, have a way of being integrated to R. For the in class problem on modeling growth and decay, i combined documents the same way, minus the instructions, so the final pdf just contains the homework questions in an interactive format, and the solutions. 
2. I am going complete writing the pre work questions for each of the in class assignments. I already have a few basic homework assignments that are designed to teach R but i think i want to split them up into individual questions so they can be referenced the same way the PAYS schedule references individual problems. 
3. I am starting to think about data Saturdays and what examples might be good for getting students interested in the data. I think sports data could be really good for reaching a large audience of interests and im sure there is a lot of it out there. But i wonder if you think it would be good to stick to larger examples( like the data4all lessons) in order to create a more cohesive lesson. 

## Date: June 3rd
1. Read through the data4all evaluation and took notes. I stated writing a document called goals and logistics to start thinking about data days and how we want that program to be run. This information can also help inform the choices and steps we take with the PAYS program as well. 
2. I found a few new sources that are high school data science programs and i want to make sure i get information from as many different places as possible so i can decide what actually will work for us and our goals. 
3. Im not really confused about anything right now but i do want to pitch a lot of my ideas for the structure of data days. I know we talked about a fwe things so i tried to come up with some concrete structure things that would help with starting to write content for the program.

## Date: June 4th
1. Started Looking into how to form the less on plan around city planning. I begin with a rough outline of the Week structure with topics for lessons and the skills that should be gained throughout the weeks. Now i've begun trying to piece the story together through datasets. Ive wrote the structure of the first lesson dealing with the history of the city plan in Los Angeles. I also started making the presentation for friday. I wanted to talk about the goals for the curriculum and why whose are our goals. Also the plans we have to achieve them through specific areas of the curriculum. 
2. Going to continue searching for relevant data sets and trying to come up with creative activities to help continue telling hte story of city planning data. 

3. I am wondering who would mostly be teaching and instructing these saturday workshops. Would it mostly be professors, or would studetns be leading a lot of the activities. I think it could be helpful to have a student mentor program but i dont know how much work people would be willing to do.

## Date: June 5th 
1. Today i began writing a lesson plan based around the `ca_tes` data set from american forests tree canopy data. The lesson starts with an introduction on why i city planning to display data science. It then goes into the meaning behind the dataset and the real-world applications of solutions. It then goes into viewing the data set, learning what an observation and observational unit is. Next, i discuss the process of questioning a data set, and learning to create informed SMART questions. The presentation then discusses the process of data wrangling using examples from the `ca_tes` data set. And finally i have created a few example visualizations to discuss the importance of meaningfully expressing and communicating your findings. This may not be the end of the lesson and there definitely is more room to add content but so far i've created somewhat of a basic structure for the lesson. 
2. I need to finish the presentation for pizza and progess, specifically pick a few examples from the lesson and explain how they connect to the goals of the project. 
3. I am trying to figure out a way to implement the mathlink cubes lesson into the full lesson plan. 

## Date: June 6th 
1. Finished presentation for pizza and progress. Created California heat map by joining the census data with the tes data set. After finding and figuring out how to use the census data i created a few data wrangling examples in the lesson plan for Saturdays. I also changed the format of the saturday lesson plan. Instead of starting with examples usages for the data verbs, i created a portion where the students would do an activity involving the mathlink cubes. I explained how they work and how they represent a data set. Then i prompt students to think about the data verbs intuitively(what you think they might mean) before giving them the definition and prompting them to physically recreate the wrangling with the cubes.
2. Begin creating a lesson with another example and new data. I could stick with the topic of city planning and do something else like traffic or transportation data, or i might shift completely.
3. Depending on the structure of the Saturdays, i will make the lessons completely different. If the workshops are going to be close in date and we expect relatively the same students to show up, then i will probably keep with the same example and add onto it to dive deeper into the data and teach more complex applications. But if each of the Saturdays are going to be completely separate, then i will probably just come up with a new example, reteaching the basic concepts i went over in the initial tree coverage lesson. 

## Date: June 9th

1. I updated some of the lesson plan for the tes example. For example i finished my infographic teaching variable types and uploaded that to a slide. Then i figured out how to create the github website and link it to a repo i created in the DS4HS org. As far as i know, it it able to be accessed publicly I worked on creating the next portion of the lesson on student projects and presentation. 
2. Start creating the teaching materials for the lesson. This will involve creating a pdf document that has the title of each slide and what information needs to be grasped from it. It will also include notes on important things to mention that are not included in the slides and also prompting the start of physical activities and student group work. 
3. What is the theme of your website called. I looked through all the quarto built in themes and i couldn't find it so i figured it was most likely custom. None of the given themes are amazing so i choose a pretty basic one. Also, is there a way to get r code to animate as a bullet point so it shows up after certain information on a slide or is it easier to just include the code on the following slide. this is for when i am presenting data wrangling questions and don't want the solution to show until students have had the chance to discuss. Also, can i change the size of photos in the presentation, they all render too small. 

## Date: June 10th 
1. Today I mostly worked on style updates to the website. I played around with a lot of the coloring and the font and changing the placement of the titles in the nav bar. I also created a logo for the program though i am open to work shopping its design (its pretty basic). I added a short introduction to the materials on the home page of the website explaining the goals of the program and where to find certain resources. Then i made some more edits to the tree equity lesson. I updated slides where i wanted r code to show incrementally. I was able to get the presentation to render as slides on the website instead of html and i looked into the multiple formats option but the code that i found didnt render correctly. Finally, i started writing the teaching materials for the tree equity lesson. I am just rendering this to a page on the website but i wonder if it would be better as a link to the pdf, or maybe include a download link at the top of page. 
2. Finish writing the instructor guide for the tree Lesson and then proofread my work from 5.2. 3. For some reason the hover color for the pages in my navbar is showing as a still rectangle over the title of the page, which makes the text illegible. I tried deconstructing my .css file but when i added everything back that i did want to include, the highlight comes back and im not sure how to fix. I also remember talking about doing the thing where you link files of different formats in the same file but i cant remeber where that was applicable so i didnge get to it today. 
## Date: June 11th
1. Today I finished the teaching materials for the Tree Equity Lesson. I did some more research about the mathlink cubes in order to explain the activity with them better. I also made a lot of style changes to the website. 
2. I am going to start working on another similar example to the tree lesson. I want to do something related to public transportation or traffic data but i think public transportation will have more applicable reasoning and results. 
3. I am still struggling with rendering to multiple formats. When i render, the html page has the other formats tab and it has the pdf linked but the pdf doesnt render correctly. I looked into it and found that having html specific syntax will not render to pdf so i tried something in the yaml to override that, but that did not work either. 

## Date June 12th 
1. I worked on finding the datasets I want to use for the lesson on public transport. It was a little difficult because a lot of the data is not complete for multiple years. I found one dataset that have information on public transportation usage from 2014-2024 but the variables are limited to ridership and mileage, not much useful information for analysis. However, I am going to include some sort of join portion in the lesson to join this data with census data in order to conduct a more useful analysis. 
2. Continue search for helpful data sets and begin writing the lesson on public transportation
3. I am still trying to figure out what I want the exact structure of the lesson to be. I know i want to include a little mre nuances questions about the data and some more advanced data wrangling topics but I am not exactly sure how that is going to look. I think running a regression to create a model for ridership over time could be a more intermediate to advanced skill that would fit that data I have well but I also want the results of the analysis to be a little more interesting. 

## Date: June 13th
1. Today I worked on the lesson for Public Transportation. First, I narrowed down the initial data set to just CA public transit systems so that it is easier to work with. I made sure to include in the instructor manual how to filter initial data to be specific to your state so it is relevant to the students. The lesson starts off with an introduction to the variables and the dataset like before, but then instead of getting into questions about the data, first students will join census data from ca with information on race, income, unemp, and other socioeconomic factors to the transportation data for a more in depth analysis. I also created an initial basic example plotting the difference ca agencies and their total riders over time. 
2. I am going to start writing the parts of the lesson that require analysis in relation to socioeconomic factors. Hopefully I was be able to create a map plot to look at accessibility of public transit in different areas and compare this to the socioeconomic factors in that area. This will then guide further analysis on those relationships. 
3. I need to think through how to structure the activities using the spatial data so they are approachable for high school students. Some of the code is a little bit difficult to understand(such as facet and leaflet)  

## Date: June 16th 2025
1. Today i found another dataset that has California public transportation data with data about public transit stops. I did a lot of wrangling on this data set so i could combine it with the geography of the census tract. And then I cleaned a version of the tidycensus data and saved it as a csv. So now i have a dataset with transit data and geography(geoid as well) and a data set with census data and geography. Hopefully this will make for a good and simple enough lesson on joining and potential map visualizations. 
2. Finish the interactive tree lesson worksheet. I started work on it today and I just have to add the last problem. 
3.In my transit data set, each stop has a value for the variable `n_hours_in_service`. A lot of stops have 0 for this value meaning they aren't ever stopped at I assume? Should this be factored into calculations(because it says something about lack of stops) or would that make results look skewed. What other variables should I pull from tidycensus to allow for more in depth exploration. Because the data requires so much cleaning, i think it will be hard for this lesson to have students doing an individual project with their own dataset. That is why i want the original dataset they see in class to be comprehensive enough to have a different research question for all the students/groups in the class. 

## Date: June 17 2025
1. I worked on writing the qmd file for the students presentation. I basically just gave them space to make a 4 slide presentation with the first slide being their research question and data, the second being their wrangling process, the third being their ggplot code and plot, and the 4th is their insights and the trends they notices from the plot. I gave a quick instruction slide that i noted should be deleted before they render. I wanted to make the presentations pretty short and uniform so its east to get through if we have a shorter day. I then worked with the mathlink cubes for a while, taking pictures of all of the different data wrangling processes and the solutions for the questions used in the tree lecture. I also wrote instructions and took pictures that explain how to put the cubes together in a data like structure thats easy for students to take a part. Finally, I did a little more work on the public transit lesson, writing the next part of the lecture that involved joining the census data with the spatial transit data.
2. I will use the mathlink cubes to represent and teach the process of joining since this goes right at the spot of the lecture i am currently writing. 
3. I'm not exactly sure if i am representing group_by and summarize correctly with the mathlink cubes. The example in the article is kind of confusing and I'm not really understanding what they are summarizing. I did group_by a certain color, and then organized that colors column by each shape in the column, but then when i summarise, im not sure if I should leave the rows where a shape repeats or if those would get filtered out with the group_by. 

## Date: June 19 2025
1. I worked on updating some of the information in 5.2. I added a few more photo examples on how to upload and being working in a .qmd file. I also added how to render your work and then save or send the pdf to yourself to turn in on gradescope. I also worked on the Hooke's law activity pdf, adding a place for the students to input the data from their lab. I also began work on the presentation for tommorows pizza and progress. I talk a little bit about what we have done with the website and our plans for how it is going to be used. 
2. I need to finish the presentation for tomorrow but i'm not exactly sure what else to include. I may talk about the work we have done with Hookes law and how we expect it to be implemented starting with PAYS on Monday.
3. I am a little confused on what exactly the Hooke_activity.pdf is supposed to look like. I know we want it to be an example for the students to se what their work should look like when they turn it in, but im not exactly sure how to do that without giving them the answers to some of the code. I think we would probably want them to see that their plot should show up underneath their code chunk, but I cant do that without actually filling in the ggplot code. I didnt want to just input meaningless variables either because i thought that would get pretty confusing. 

## Date: June 24th 
1. I finished all the in class materials for week 1 and week 2. I did a little bit more work on the planetary orbits lab though i think we may go over it and change some of the material. 
2. Finish editing planetary orbits and move onto the next 2 weeks of in class problems. 
3. I have a few questions today. First, Should all of the homework questions for week 1 be integrated into one singular .qmd file that way students dont have to keep downloading materials and everything can be kept. little more put together. I also wondered, however, if the in class assignments even needed to be rendered to pdf because they already have the instructions printed and i dont think they will be turning in a pdf version of their in class work. 

## Date: June 25th 
1. Today I sat in with the Pays class and helped out with the Hooke's Lab activity. There was definitely a lot of confusion, as we expected, but i think a lot of the students started to get a hang of things by the end of class. I also stopped my the TA session to make sure everyone had the lab assignment turned in correctly. I notices a lot of the students didnt go through the assignment in order? Some skipped to the r chunks and others tried to skip to the end to see what questions they had to answer. I saw this caused a lot of confusion with the work flow of the code chunks within the questions. I stated writing the extra lesson for next Wednesdays class with the olympic dataset and i made sure to emphasize the importance of following along with the lesson chronologically. 
2. Finish working on the olympics lesson. I also will sit in for the Pays class tomorrow to help them get started on the area of stars lab. 
3. As of right now, i'm just writing wednesdays work how I would write any of the other in-class problems in a qmd file with instructions. But im wondering if it would be beneficial to have slides or some other presentation material for prof yassine. Today, there was little presentation in class an the students mostly just started work in groups right away and occasionally prof yassine would jump in to give tips so im not exactly sure if it works with his teaching style but i could definitely offer if he would like something like that. 